# Generated by Django 6.0 on 2026-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='podiums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='pole_positions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='race_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='world_championships',
            field=models.IntegerField(default=0),
        ),
    ]
