# Generated by Django 6.0 on 2026-01-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sprint_race',
            field=models.BooleanField(default=False),
        ),
    ]
