# Generated by Django 6.0 on 2026-01-23 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_driver_podiums_driver_pole_positions_and_more'),
        ('schedule', '0003_alter_schedule_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results_finalized', models.BooleanField(default=False)),
                ('dnf_drivers', models.ManyToManyField(blank=True, related_name='dnf_races', to='drivers.driver')),
                ('driver_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotd_results', to='drivers.driver')),
                ('fastest_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastest_lap_results', to='drivers.driver')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place_results', to='drivers.driver')),
                ('pole_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pole_results', to='drivers.driver')),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='schedule.schedule')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place_results', to='drivers.driver')),
                ('sprint_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_first_results', to='drivers.driver')),
                ('sprint_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_second_results', to='drivers.driver')),
                ('sprint_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_third_results', to='drivers.driver')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place_results', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='UserSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('correct_poles', models.IntegerField(default=0)),
                ('correct_wins', models.IntegerField(default=0)),
                ('races_participated', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Season Stats',
                'ordering': ['-total_points', '-correct_wins', '-correct_poles', '-races_participated'],
            },
        ),
        migrations.CreateModel(
            name='RacePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('picks_locked', models.BooleanField(default=False)),
                ('driver_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotd_picks', to='drivers.driver')),
                ('fastest_lap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastest_lap_picks', to='drivers.driver')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place_picks', to='drivers.driver')),
                ('pole_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pole_picks', to='drivers.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='schedule.schedule')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place_picks', to='drivers.driver')),
                ('sprint_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_first_picks', to='drivers.driver')),
                ('sprint_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_second_picks', to='drivers.driver')),
                ('sprint_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_third_picks', to='drivers.driver')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_place_picks', to='drivers.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-race__date'],
                'unique_together': {('user', 'race')},
            },
        ),
    ]
