# Generated by Django 6.0 on 2026-01-24 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_podiums_driver_pole_positions_and_more'),
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racepick',
            name='driver_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dotd_picks', to='drivers.driver'),
        ),
    ]
