# Generated by Django 6.0 on 2026-01-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_podiums_driver_pole_positions_and_more'),
        ('picks', '0002_alter_racepick_driver_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racepick',
            name='driver_of_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dotd_picks', to='drivers.driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='driver_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dotd_results', to='drivers.driver'),
        ),
    ]
